OPENAI_API_KEY = "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"
NOTION_TOKEN = "secret_ACWipYLLkakKzVBGixKUEsaLcQjP8C1xMLuUAIGMztH"
DATABASE_ID = "b75f7a4060254eff93f28888448c0df9"
STORE_INFORMATION_DB_ID = "6927738770fe4b80af26e53d95f27235"