OPENAI_API_KEY = "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"
NOTION_TOKEN = "secret_ACWipYLLkakKzVBGixKUEsaLcQjP8C1xMLuUAIGMztH"
DATABASE_ID = "b75f7a4060254eff93f28888448c0df9"
STORE_INFORMATION_DB_ID = "6927738770fe4b80af26e53d95f27235"